# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Agendamento de builds com scheduler cron

schedules: 
  - cron: "35 10 * * *"
    displayName: Agendamento pelo YAML
    branches:
      include:
        - master
    always: true

pool: 
  vmImage: 'windows-2019'

steps: # Scripts para escrita no log uma mensagem
- script: echo Primeira pipeline com YAML!
  displayName: 'Script no YAML'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
