# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: # Gatilho na branch master, sempre que a master for atualizada esse gatilho será acionado
- feature/* 

pool: # Um agent pool com o sistema ubunto com a ultima versão disponivel
  vmImage: 'ubuntu-latest'

steps: # Scripts para escrita no log uma mensagem
- script: echo Primeira pipeline com YAML!
  displayName: 'Script no YAML'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
