
pool: 
 vmImage: 'ubuntu-latest'

steps:
  - script: echo "Using Tasks"
    displayName: "Run Script"
  - task: PowerShell@2
    inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          
          Write-Host "Using Tasks with YAML"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '.'
      ArtifactName: 'drop-yaml'
      publishLocation: 'Container' 